// Generated by gencpp from file camera/PhotoServiceRequest.msg
// DO NOT EDIT!


#ifndef CAMERA_MESSAGE_PHOTOSERVICEREQUEST_H
#define CAMERA_MESSAGE_PHOTOSERVICEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace camera
{
template <class ContainerAllocator>
struct PhotoServiceRequest_
{
  typedef PhotoServiceRequest_<ContainerAllocator> Type;

  PhotoServiceRequest_()
    : shelf_id()  {
    }
  PhotoServiceRequest_(const ContainerAllocator& _alloc)
    : shelf_id(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _shelf_id_type;
  _shelf_id_type shelf_id;





  typedef boost::shared_ptr< ::camera::PhotoServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::camera::PhotoServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PhotoServiceRequest_

typedef ::camera::PhotoServiceRequest_<std::allocator<void> > PhotoServiceRequest;

typedef boost::shared_ptr< ::camera::PhotoServiceRequest > PhotoServiceRequestPtr;
typedef boost::shared_ptr< ::camera::PhotoServiceRequest const> PhotoServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::camera::PhotoServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::camera::PhotoServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace camera

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'camera': ['/home/eaibot/nju_ws/src/camera/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::camera::PhotoServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::camera::PhotoServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera::PhotoServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera::PhotoServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera::PhotoServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera::PhotoServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::camera::PhotoServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6fb1aafe191b3038cc37331cd337f99f";
  }

  static const char* value(const ::camera::PhotoServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6fb1aafe191b3038ULL;
  static const uint64_t static_value2 = 0xcc37331cd337f99fULL;
};

template<class ContainerAllocator>
struct DataType< ::camera::PhotoServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "camera/PhotoServiceRequest";
  }

  static const char* value(const ::camera::PhotoServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::camera::PhotoServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
string shelf_id\n\
";
  }

  static const char* value(const ::camera::PhotoServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::camera::PhotoServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.shelf_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PhotoServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::camera::PhotoServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::camera::PhotoServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "shelf_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.shelf_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAMERA_MESSAGE_PHOTOSERVICEREQUEST_H
