// Generated by gencpp from file camera/PhotoshelfServiceResponse.msg
// DO NOT EDIT!


#ifndef CAMERA_MESSAGE_PHOTOSHELFSERVICERESPONSE_H
#define CAMERA_MESSAGE_PHOTOSHELFSERVICERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace camera
{
template <class ContainerAllocator>
struct PhotoshelfServiceResponse_
{
  typedef PhotoshelfServiceResponse_<ContainerAllocator> Type;

  PhotoshelfServiceResponse_()
    : province_names()
    , positions_x()
    , positions_y()
    , codes()  {
    }
  PhotoshelfServiceResponse_(const ContainerAllocator& _alloc)
    : province_names(_alloc)
    , positions_x(_alloc)
    , positions_y(_alloc)
    , codes(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _province_names_type;
  _province_names_type province_names;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _positions_x_type;
  _positions_x_type positions_x;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _positions_y_type;
  _positions_y_type positions_y;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _codes_type;
  _codes_type codes;





  typedef boost::shared_ptr< ::camera::PhotoshelfServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::camera::PhotoshelfServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PhotoshelfServiceResponse_

typedef ::camera::PhotoshelfServiceResponse_<std::allocator<void> > PhotoshelfServiceResponse;

typedef boost::shared_ptr< ::camera::PhotoshelfServiceResponse > PhotoshelfServiceResponsePtr;
typedef boost::shared_ptr< ::camera::PhotoshelfServiceResponse const> PhotoshelfServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::camera::PhotoshelfServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::camera::PhotoshelfServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace camera

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'camera': ['/home/eaibot/nju_ws/src/camera/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::camera::PhotoshelfServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::camera::PhotoshelfServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera::PhotoshelfServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera::PhotoshelfServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera::PhotoshelfServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera::PhotoshelfServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::camera::PhotoshelfServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5fbec0c698813ceefcd320f6e0b0177c";
  }

  static const char* value(const ::camera::PhotoshelfServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5fbec0c698813ceeULL;
  static const uint64_t static_value2 = 0xfcd320f6e0b0177cULL;
};

template<class ContainerAllocator>
struct DataType< ::camera::PhotoshelfServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "camera/PhotoshelfServiceResponse";
  }

  static const char* value(const ::camera::PhotoshelfServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::camera::PhotoshelfServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] province_names\n\
int32[] positions_x\n\
int32[] positions_y\n\
int32[] codes\n\
";
  }

  static const char* value(const ::camera::PhotoshelfServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::camera::PhotoshelfServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.province_names);
      stream.next(m.positions_x);
      stream.next(m.positions_y);
      stream.next(m.codes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PhotoshelfServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::camera::PhotoshelfServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::camera::PhotoshelfServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "province_names[]" << std::endl;
    for (size_t i = 0; i < v.province_names.size(); ++i)
    {
      s << indent << "  province_names[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.province_names[i]);
    }
    s << indent << "positions_x[]" << std::endl;
    for (size_t i = 0; i < v.positions_x.size(); ++i)
    {
      s << indent << "  positions_x[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.positions_x[i]);
    }
    s << indent << "positions_y[]" << std::endl;
    for (size_t i = 0; i < v.positions_y.size(); ++i)
    {
      s << indent << "  positions_y[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.positions_y[i]);
    }
    s << indent << "codes[]" << std::endl;
    for (size_t i = 0; i < v.codes.size(); ++i)
    {
      s << indent << "  codes[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.codes[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAMERA_MESSAGE_PHOTOSHELFSERVICERESPONSE_H
