// Generated by gencpp from file camera/PhotoServiceResponse.msg
// DO NOT EDIT!


#ifndef CAMERA_MESSAGE_PHOTOSERVICERESPONSE_H
#define CAMERA_MESSAGE_PHOTOSERVICERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace camera
{
template <class ContainerAllocator>
struct PhotoServiceResponse_
{
  typedef PhotoServiceResponse_<ContainerAllocator> Type;

  PhotoServiceResponse_()
    : provinces()
    , positions_x()
    , positions_y()  {
    }
  PhotoServiceResponse_(const ContainerAllocator& _alloc)
    : provinces(_alloc)
    , positions_x(_alloc)
    , positions_y(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _provinces_type;
  _provinces_type provinces;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _positions_x_type;
  _positions_x_type positions_x;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _positions_y_type;
  _positions_y_type positions_y;





  typedef boost::shared_ptr< ::camera::PhotoServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::camera::PhotoServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PhotoServiceResponse_

typedef ::camera::PhotoServiceResponse_<std::allocator<void> > PhotoServiceResponse;

typedef boost::shared_ptr< ::camera::PhotoServiceResponse > PhotoServiceResponsePtr;
typedef boost::shared_ptr< ::camera::PhotoServiceResponse const> PhotoServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::camera::PhotoServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::camera::PhotoServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace camera

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'camera': ['/home/eaibot/nju_ws/src/camera/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::camera::PhotoServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::camera::PhotoServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera::PhotoServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera::PhotoServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera::PhotoServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera::PhotoServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::camera::PhotoServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "62345d15c2a8f524d173f0fa9a44e6e3";
  }

  static const char* value(const ::camera::PhotoServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x62345d15c2a8f524ULL;
  static const uint64_t static_value2 = 0xd173f0fa9a44e6e3ULL;
};

template<class ContainerAllocator>
struct DataType< ::camera::PhotoServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "camera/PhotoServiceResponse";
  }

  static const char* value(const ::camera::PhotoServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::camera::PhotoServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] provinces\n\
float32[] positions_x\n\
float32[] positions_y\n\
";
  }

  static const char* value(const ::camera::PhotoServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::camera::PhotoServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.provinces);
      stream.next(m.positions_x);
      stream.next(m.positions_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PhotoServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::camera::PhotoServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::camera::PhotoServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "provinces[]" << std::endl;
    for (size_t i = 0; i < v.provinces.size(); ++i)
    {
      s << indent << "  provinces[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.provinces[i]);
    }
    s << indent << "positions_x[]" << std::endl;
    for (size_t i = 0; i < v.positions_x.size(); ++i)
    {
      s << indent << "  positions_x[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.positions_x[i]);
    }
    s << indent << "positions_y[]" << std::endl;
    for (size_t i = 0; i < v.positions_y.size(); ++i)
    {
      s << indent << "  positions_y[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.positions_y[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAMERA_MESSAGE_PHOTOSERVICERESPONSE_H
